project/my_site/my_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('website.urls')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

project/my_site/website/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.urls import path, include
from . import views

from website.customer import views as customer_view
from website.driver import views as driver_view
from .forms import LoginForm

customer_urlpatterns = [
    path('', customer_view.home, name='home'),
    path('profile/', customer_view.profile, name='profile'),
    path('create_order/', customer_view.create_order, name='create_order'),
    path('orders/current/', customer_view.orders, name='orders'),
    path('orders/archived/', customer_view.archived_orders, name='archived'),
    path('orders/<order_id>/', customer_view.details, name='details'),
]

driver_urlpatterns = [
    path('', driver_view.driver_page, name='home'),
    path('jobs/', driver_view.jobs, name="jobs"),
    path('my_job/', driver_view.myjob, name="myjob"),
    path('dashboard/', driver_view.dashboard, name="dashboard"),
    path('jobs/<id>/', driver_view.available_jobs, name='available_jobs'),
]

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    
    
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
   
    
    path('customer/', include((customer_urlpatterns,'customer'), namespace='customer')),
    path('driver/', include((driver_urlpatterns, 'driver')))

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
   urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/my_site/website/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid
from django.utils import timezone

class Driver(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='driver/avatar/', blank=True, null=True)
    phone_number = models.CharField(max_length=12, blank=True)
    earnings = models.FloatField(default=0.0)

    def __str__(self) -> str:
        return self.user.get_full_name()

class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='customer/avatar/', blank=True, null=True)
    phone_number = models.CharField(max_length=12, blank=True)
    adress = models.CharField(max_length=100, blank=True)

    def __str__(self) -> str:
        return self.user.get_full_name()
    
class Category(models.Model):
    slug = models.CharField(max_length=255, unique=True)
    name = models.CharField(max_length=255)

    def __str__(self) -> str:
        return self.name

class Order(models.Model):
    SMALL_SIZE = 'small'
    MEDIUM_SIZE = 'medium'
    LARGE_SIZE = 'large'
    SIZES = (
        (SMALL_SIZE, 'Small'),
        (MEDIUM_SIZE, 'Medium'),
        (LARGE_SIZE, 'Large'),
    )

    CREATING_STATUS = 'creating'
    PROCESSING_STATUS = 'processing'
    PICKING_STATUS = 'picking'
    DELIVERY_STATUS = 'delivery'
    COMPLETED_STATUS = 'completed'
    CANCELED_STATUS = 'canceled'
    STATUS = (
        (CREATING_STATUS, 'Creating'),
        (PROCESSING_STATUS, 'Processing'),
        (PICKING_STATUS, 'Picking'),
        (DELIVERY_STATUS, 'Delivery'),
        (COMPLETED_STATUS, 'Completed'),
        (CANCELED_STATUS, 'Canceled'),
    )

    # Step 1
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    driver = models.ForeignKey(Driver, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True)
    size = models.CharField(max_length=20, choices=SIZES, default=SMALL_SIZE)
    quantity = models.IntegerField(default=1)
    photo = models.ImageField(upload_to='order/photos/')
    status = models.CharField(max_length=20, choices=STATUS, default=CREATING_STATUS)
    create_at = models.DateField(default=timezone.now)

    # Step 2
    pickup_adress = models.CharField(max_length=255, blank=True)
    pickup_name = models.CharField(max_length=255, blank=True)
    pickup_phone = models.CharField(max_length=12, blank=True)

    # Step 3
    delivery_address = models.CharField(max_length=255, blank=True)
    delivery_name = models.CharField(max_length=255, blank=True)
    delivery_phone = models.CharField(max_length=12, blank=True)

    # Step 4
    CARD_PAYMENT = 'card payment'
    CASH_PAYMENT = 'cash payment'
    PAYMENT = (
        (CARD_PAYMENT, 'Card Payment'),
        (CASH_PAYMENT, 'Cash Payment')
    )
    payment_methods = models.CharField(max_length=50, choices=PAYMENT, default=CASH_PAYMENT)
    price = models.FloatField(default=15000.0)

    def __str__(self):
        return self.name

project/my_site/website/driver/forms.py
from django import forms
from django.contrib.auth.models import User
from website.models import Driver

class BasicUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = '__all__'

class BasicDriverForm(forms.ModelForm):
    class Meta:
        model = Driver
        fields = ('avatar', 'phone_number',)

project/my_site/website/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-50 py-2 px-2 rounded'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-50 py-2 px-2 rounded'
    }))

class SignupForm(UserCreationForm):
    first_name = forms.CharField(max_length=150)
    last_name = forms.CharField(max_length=150)

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2')

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-100 py-2 px-2 rounded'
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your email',
        'class': 'w-100 py-2 px-2 rounded'
    }))
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your first name',
        'class': 'w-100 py-2 px-2 rounded'
    }))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your last name',
        'class': 'w-100 py-2 px-4 rounded'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-100 py-2 px-4 rounded'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Password confirmation',
        'class': 'w-100 py-2 px-4 rounded'
    }))

class EditProfile(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name')



        

project/my_site/website/customer/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from website.customer import forms

from django.contrib import messages
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash

from website.models import Order
# Create your views here.
@login_required()
def home(request):
    return render(request, 'customer/customer_page.html')

@login_required(login_url='login/?next=/customer/')
def profile(request):
    user_form = forms.BasicUserForm(instance=request.user)
    customer_form = forms.BasicCustomerForm(instance=request.user.customer)
    password_form = PasswordChangeForm(request.user)

    if request.POST.get('action') == 'update_profile':
        if request.method == 'POST':
            user_form = forms.BasicUserForm(request.POST, instance=request.user)
            customer_form = forms.BasicCustomerForm(request.POST, request.FILES, instance=request.user.customer)

            if user_form.is_valid() and customer_form.is_valid():
                user_form.save()
                customer_form.save()
                return redirect(reverse('core:customer:home'))
            
    elif request.POST.get('action') == 'update_password':
        password_form = PasswordChangeForm(request.user, request.POST)
        if password_form.is_valid():
            user = password_form.save()
            update_session_auth_hash(request, user)
            return redirect(reverse('core:customer:home'))
        
    return render(request, 'customer/profile.html', {
        'user_form' : user_form,
        'customer_form': customer_form,
        'password_form': password_form,
    })

@login_required(login_url='login/?next=/customer/')
def create_order(request):
    current_customer = request.user.customer
    medium_price = 25000.0
    large_price = 35000.0
    creating_order = Order.objects.filter(customer=current_customer, status=Order.CREATING_STATUS).last()
    step1_form = forms.OrderCreateStep1Form(instance=creating_order)
    step2_form = forms.OrderCreateStep2Form(instance=creating_order)
    step3_form = forms.OrderCreateStep3Form(instance=creating_order)
    step4_form = forms.OrderCreateStep4Form(instance=creating_order)
    
    if request.method == 'POST':
        if request.POST.get('step') == '1':
            step1_form = forms.OrderCreateStep1Form(request.POST, request.FILES, instance=creating_order)
            if step1_form.is_valid():
                creating_order = step1_form.save(commit=False)
                creating_order.customer = current_customer
                if creating_order.size == 'medium':
                    creating_order.price = medium_price 
                elif creating_order.size == 'large':
                     creating_order.price = large_price
                creating_order.save()
                return redirect(reverse('core:customer:create_order'))
            
        elif request.POST.get('step') == '2':
            step2_form = forms.OrderCreateStep2Form(request.POST, instance=creating_order)
            if step2_form.is_valid():    
                creating_order = step2_form.save()
                return redirect(reverse('core:customer:create_order'))
            
        elif request.POST.get('step') == '3':
            step3_form = forms.OrderCreateStep3Form(request.POST, instance=creating_order)
            if step3_form.is_valid():    
                creating_order = step3_form.save()
                return redirect(reverse('core:customer:create_order'))

        elif request.POST.get('step') == '4':
            step4_form = forms.OrderCreateStep4Form(request.POST, instance=creating_order)
            if step4_form.is_valid(): 
                creating_order.status = Order.PROCESSING_STATUS
                
                creating_order = step4_form.save()
                return redirect(reverse('core:customer:orders'))

    if not creating_order:
        current_step = 1
    elif creating_order.delivery_name:
        current_step = 4
    elif creating_order.pickup_name:
        current_step = 3
    else:
        current_step = 2

    return render(request, 'customer/create_order.html', {   
        'order' : creating_order,
        'current_step': current_step,
        'step1_form' : step1_form,
        'step2_form' : step2_form,
        'step3_form' : step3_form,
        'step4_form' : step4_form,
    })
    
@login_required(login_url='login/?next=/customer/')
def orders(request):
    order = Order.objects.filter(
        customer=request.user.customer,
        status__in = [
            Order.PROCESSING_STATUS,
            Order.PICKING_STATUS,
            Order.DELIVERY_STATUS,
        ]
    )

    return render(request, 'customer/orders.html', {
        'order': order
    })

@login_required(login_url='login/?next=/customer/')
def archived_orders(request):
    order = Order.objects.filter(
        customer=request.user.customer,
        status__in = [
            Order.COMPLETED_STATUS,
            Order.CANCELED_STATUS,
        ]
    )

    return render(request, 'customer/orders.html', {
        'order': order
    })

@login_required(login_url='login/?next=/customer/')
def details(request, order_id):
    order = Order.objects.get(id=order_id)

    if request.method == 'POST' and order.status == Order.PROCESSING_STATUS:
        order.status = Order.CANCELED_STATUS
        order.save()
        return redirect(reverse('core:customer:archived'))

    return render(request, 'customer/details.html', {
        'order': order
    })

project/my_site/website/driver/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from website.driver import forms
import pandas as pd
import numpy as np
from website.models import Order

@login_required()
def driver_page(request):
    return render(request, 'driver/driver_page.html')

@login_required(login_url='/signup/?next=/driver/')
def available_jobs(request, id):
    job = Order.objects.get(id=id)
    
    if not job:
        return redirect(reverse('core:driver:jobs'))
    
    if request.method == 'POST' and job.status == Order.PROCESSING_STATUS:
        job.driver = request.user.driver
        job.status = Order.PICKING_STATUS
        job.save()
        return redirect(reverse('core:driver:myjob'))
    
    return render(request, 'driver/available_jobs.html', {
         'item' : job
    })

@login_required(login_url='/signup/?next=/driver/')
def jobs(request):
    job = Order.objects.filter(status=Order.PROCESSING_STATUS)

    return render(request, 'driver/jobs.html', {
        'job': job
    })

@login_required(login_url='/signup/?next=/driver/')
def myjob(request):
    job = Order.objects.filter(
        driver=request.user.driver,
        status__in = [
            Order.PICKING_STATUS,
            Order.DELIVERY_STATUS,
        ]
    )

    if request.method == 'POST':
        if request.POST.get('status') == 'delivery':
            for j in job:
                j.status = Order.DELIVERY_STATUS
                j.save()
                return redirect(reverse('core:driver:myjob'))
        elif request.POST.get('status') == 'cancel':
            for j in job:
                j.status = Order.PROCESSING_STATUS
                j.save()
                return redirect(reverse('core:driver:jobs'))
        elif request.POST.get('status') == 'complete':
            for j in job:
                j.status = Order.COMPLETED_STATUS
                j.save()
                return redirect(reverse('core:driver:home'))

    return render(request, 'driver/my_job.html', {
        'myjob' : job
    })

@login_required(login_url='/signup/?next=/driver/')
def dashboard(request):
    driver = request.user.driver
    
    order = Order.objects.filter(
        driver = driver,
        status__in = [
            Order.COMPLETED_STATUS
        ]
    )
    order_item = Order.objects.filter(
        driver = driver,
        status__in = [
            Order.COMPLETED_STATUS
        ]
    ).values()

    df = pd.DataFrame(order_item).sort_values('size', ascending=False)
    df_name = df['name'].tolist()
    df_price = df['price'].tolist()
    df_size = df['size'].value_counts().tolist()
    quantity = df.shape[0]

    for item in order:
        driver.earnings += item.price
         

    return render(request, 'driver/dashboard.html', {
        'order' : order,
        'df' : df,
        'df_name': df_name,
        'df_price': df_price,
        'df_size' : df_size,
        'earnings_month' : driver.earnings,
        'quantity' : quantity
    })

project/my_site/website/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import SignupForm, EditProfile
from django.urls import reverse



# Create your views here.
def index(request):
    return render(request, 'core/index.html')

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            
            return redirect('/login/')
    else:
        form = SignupForm()    
    
    context = {
            'form' : form
    }
    
    return render(request, 'core/signup.html', context)

project/my_site/website/templates/driver/available_jobs.html
{% extends 'driver/driver_page.html'%}

{% block content %}
<div class="container mt-5">

    <div class="media mb-4 ">
        <img src="{{ item.photo.url }}" class="rounded-lg mr-3" width="150" height="150">
        <div class="media-body">
            <h4>{{ item.name }}</h4>
            <p class="text-secondary">{{ item.description }}</p>
    
            <div class="row mb-3">
                <div class="col-lg-3">
                    <small class="text-secondary">CATEGORY</small><br>
                    <span><b>{{ item.category.name }}</b></span>
                </div>
    
                <div class="col-lg-3">
                    <small class="text-secondary">SIZE</small><br>
                    <span><b>{{ item.get_size_display }}</b></span>
                </div>
                <div class="col-lg-3">
                    <small class="text-secondary">PRICE</small><br>
                    <span><b>{{ item.price }} VND</b></span>
                </div>
                <div class="col-lg-3">
                    <small class="text-secondary">QUANTITY</small><br>
                    <span><b>{{ item.quantity }}</b></span>
                </div>
            </div>
            
            <hr>
            <b class="text-primary">DELIVERY INFORMATION</b>
            <div class=" card mt-2 mb-5">
                <div class="card-body p-4">
                    <h4 class="mb-3">Pickup</h4>
    
                    <div class="row">
                        <div class="col">
                            <b>Name: </b>
                            <span>{{ item.pickup_name }}</span><br>
                            <b>Phone number: </b>
                            <span>{{ item.pickup_phone }}</span><br>
                            <b>Address: </b>
                            <span>{{ item.pickup_adress }}</span>
                        </div> 
                    </div>
    
                </div>
                <hr>
                <div class="card-body p-4">
                    <h4 class="mb-3">Delivery</h4>
    
                    <div class="row">
                        <div class="col">
                            <b>Name: </b>
                            <span>{{ item.delivery_name }}</span><br>
                            <b>Phone number: </b>
                            <span>{{ item.delivery_phone }}</span><br>
                            <b>Address: </b>
                            <span>{{ item.delivery_address }}</span>
                        </div> 
                    </div>
    
                </div>
                 
                    
            </div>
            {% if item.status == 'processing' %}
                <form method="post" class="text-right">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Picking</button>
                </form>
            {% endif %}
        </div>
    </div>

</div>



{% endblock %}

project/my_site/website/templates/driver/driver_page.html
{% extends "core/index.html" %}
{% load static %}
{% block content %}
<div class="container mt-4 pt-3 pb-3">
    <div class="row">
        <div class="col">
            <div class=" text-center">
                <img  src="{% if request.user.driver.avatar %} {{ request.user.drvier.avatar.url }} {% else %} {% static 'images/avatar_blank.jpg' %} {% endif %}" alt="Avatar" class="rounded-circle mx-auto" width="100" height="100">
                <h4 class="p-5 text-center">{{ request.user.get_full_name | title }}</h4>
                <p class="text-secondary">Bio</p>
            </div>
        
            <ul class="list-group">
                <li class="list-group-item"><a href="{% url 'core:driver:jobs' %}" class="text-decoration-none text-dark">Job</a></li>
                <li class="list-group-item"><a href="{% url 'core:driver:myjob' %}" class="text-decoration-none text-dark">My job</a></li>
                <li class="list-group-item"><a href="{% url 'core:driver:dashboard' %}" class="text-decoration-none text-dark">Dashboard</a></li>
            </ul>
        </div>
        <div class="col">
            {% block main%}

            {% endblock %}
        </div>  
    </div>
{% endblock %}

project/my_site/website/templates/driver/jobs.html
{% extends 'driver/driver_page.html'%}

{% block content %}
<div class="container">
    <div class="list-group mt-3">
        <h4 class="text-secondary">List Order</h4>
        {% if job %}
            {% for item in job %}
                <a href="{% url 'core:driver:available_jobs' item.id %}" class="list-group-item list-group-item-action">
                    <div class="media mb-2">
                        <img src="{{ item.photo.url }}" class="rounded-lg mr-3" width="100" height="100">
                        <div class="media-body">
                            <div class="row">
    
                                <div class="col-lg-9">
                                    <h5 class="mb-1">{{ item.name }}</h5>
                                    <p>{{ item.description }}</p>
                                    <i class="fa-solid fa-car"></i>
                                    <small>{{item.distance}} Km</small>
                                    <i class="fa-regular fa-clock"></i>
                                    <small>{{item.duration}} mins</small>
                                    <div class="d-flex mb-4">
                                        
                                        <div class="ml-2">
                                            <b>{{ item.pickup_name }}</b><br>
                                            <i class="fas fa-map-marker-alt"></i>
                                            <small>{{item.pickup_adress}}</small>
                                        </div>
                                    </div>
    
                                    <div class="d-flex ">
                                        
                                        <div class="ml-2">
                                            <b>{{ item.delivery_name }}</b><br>
                                            <i class="fa-solid fa-location-crosshairs"></i>
                                            <small>{{item.delivery_address}}</small>
                                        </div>
                                        
                                    </div>
                                    <div class="text-right">
                                        <h4 class="mb-1">Total: {{ item.price }} </h4>
                                    </div>
                                </div>
    
                                <div class="col-lg-3 text-right d-flex flex-column justify-content-between">
                                    <div><span class="badge badge-warning mb-2">{{ item.get_status_display }}</span></div><br>
                                    
                                    
                                </div>
                                
                            </div>
                        </div>
                    </div>
                </a>
                
            {% endfor %}
        {% else %}
        <div class="card">
            <div class="card-body text-center">
                Nothing to show here yet.
            </div>
        </div>
        {% endif %}
    </div>
</div>
    
{% endblock %}

project/my_site/website/templates/driver/my_job.html
{% extends 'driver/driver_page.html'%}

{% block content %}
<div class="container">
    <div class="list-group mt-3">
        <h4 class="text-secondary">Current job  </h4>
        {% if myjob %}
            {% for item in myjob %}
                <a href="{% url 'core:driver:available_jobs' item.id %}" class="list-group-item list-group-item-action">
                    <div class="media mb-2">
                        <img src="{{ item.photo.url }}" class="rounded-lg mr-3" width="100" height="100">
                        <div class="media-body">
                            <div class="row">
    
                                <div class="col-lg-9">
                                    <h5 class="mb-1">{{ item.name }}</h5>
                                    <p>{{ item.description }}</p>
                                    
                                    <div class="d-flex mb-4">
                                        
                                        <div class="ml-2">
                                            <b>{{ item.pickup_name }}</b><br>
                                            <i class="fas fa-map-marker-alt"></i>
                                            <small>{{item.pickup_adress}}</small>
                                        </div>
                                    </div>
    
                                    <div class="d-flex ">
                                        
                                        <div class="ml-2">
                                            <b>{{ item.delivery_name }}</b><br>
                                            <i class="fa-solid fa-location-crosshairs"></i>
                                            <small>{{item.delivery_address}}</small>
                                        </div>
                                        
                                    </div>
                                    <div class="text-right">
                                        <h4 class="mb-1">Total: {{ item.price }} </h4>
                                    </div>
                                </div>
    
                                <div class="col-lg-3 text-right d-flex flex-column justify-content-between">
                                    <div><span class="badge badge-warning mb-2">{{ item.get_status_display }}</span></div><br>
                                    
                                    {% if item.status == 'picking' %}
                                    <form method="post">
                                        {% csrf_token %}
                                        <input type="hidden" name="status" value="delivery">
                                        <button type="submit" class="btn btn-outline-warning">Delivery</button>
                                        
                                    </form>
                                    
                                    <form method="POST">
                                        {% csrf_token %}
                                        <input type="hidden" name="status" value="cancel">
                                        <button type="submit" class="btn btn-outline-danger">Cancel</button>
                                    </form>

                                    {% endif %}

                                    {% if item.status == 'delivery' %}
                                    <form method="post" class="text-right">
                                        {% csrf_token %}
                                        <input type="hidden" name="status" value="complete">
                                        <button type="submit" class="btn btn-success">Complete</button>
                                    </form>
                                    {% endif %}

                                    
                                </div>
                                
                            </div>
                        </div>
                    </div>
                </a>
                
            {% endfor %}
        {% else %}
        <div class="card">
            <div class="card-body text-center">
                Nothing to show here yet.
            </div>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

project/my_site/website/templates/driver/profile.html
{% extends 'driver/driver_page.html' %}

{% block content %}
    <div class="container m-5">
    <b class="text-secondary text-info">Basic Information</b>
    <div class="card bg-light mt-2 mb-5">
        <div class="card-body">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="mb-3">
                    <label class="m-2 d-inline-block">First name:</label>
                    {{ user_form.first_name }}
                </div>

                <div class="mb-3">
                    <label class="m-2 d-inline-block">Last name:</label>
                    {{ user_form.last_name }} 
                </div>
                <div class="mb-3">
                    <label class="m-2 d-inline-block">Phone:</label>
                    {{ driver_form.phone_number }} 
                </div>
                
                <div class="mb-3">
                    <label class="m-2 d-inline-block">Avatar</label><br>
                    {{ driver_form.avatar }} 
                </div>
                <input type="hidden" name="action" value="update_profile">
                <button type="submit" class="mt-3 btn btn-warning text-dark">Save</button>
            </form>
        </div>
    </div>

    <b class="text-secondary text-info">Change Password</b>
    <div class="card bg-light mt-2 mb-5">
        <div class="card-body">
            <form method="POST">
                {% csrf_token %}
                {{ password_form.as_p }}
                <input type="hidden" name="action" value="update_password">
                <button type="submit" class="mt-3 btn btn-warning text-dark">Save</button>
            </form>
        </div>
    </div>

    
</div>
{% endblock %}