project/my_site/my_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('website.urls')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

project/my_site/website/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.urls import path, include
from . import views

from website.customer import views as customer_view
from website.driver import views as driver_view
from .forms import LoginForm

customer_urlpatterns = [
    path('', customer_view.home, name='home'),
    path('profile/', customer_view.profile, name='profile'),
    path('create_order/', customer_view.create_order, name='create_order'),
    path('orders/current/', customer_view.orders, name='orders'),
    path('orders/archived/', customer_view.archived_orders, name='archived'),
    path('orders/<order_id>/', customer_view.details, name='details'),
]

driver_urlpatterns = [
    path('', driver_view.driver_page, name='home'),
    path('jobs/', driver_view.jobs, name="jobs"),
    path('my_job/', driver_view.myjob, name="myjob"),
    path('dashboard/', driver_view.dashboard, name="dashboard"),
    path('jobs/<id>/', driver_view.available_jobs, name='available_jobs'),
]

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    
    
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
   
    
    path('customer/', include((customer_urlpatterns,'customer'), namespace='customer')),
    path('driver/', include((driver_urlpatterns, 'driver')))

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
   urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/my_site/website/customer/forms.py
from django import forms
from django.contrib.auth.models import User
from website.models import Customer, Order

class BasicUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name')
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your first name',
        'class': 'w-100 py-2 px-2 rounded'
    }))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your  last name',
        'class': 'w-100 py-2 px-2 rounded'
    }))

class BasicCustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ('avatar', 'phone_number', 'adress',)

    phone_number = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your phone number',
        'class': 'w-100 py-2 px-2 rounded'
    }))
    adress = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Enter your address',
        'class': 'w-100 py-2 px-2 rounded'
    }))


class OrderCreateStep1Form(forms.ModelForm):
    class Meta:
        model = Order
        fields = ('name', 'description', 'category', 'size', 'quantity', 'photo')

    name = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Enter item name',
        'class': 'w-100 py-2 px-2 rounded'
    }))
    description = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Description',
        'class': 'w-100 py-2 px-2 rounded'
    }))
    
class OrderCreateStep2Form(forms.ModelForm):
    pickup_adress = forms.CharField(required=True)
    pickup_name = forms.CharField(required=True)
    pickup_phone = forms.CharField(required=True)

    class Meta:
        model = Order
        fields = ('pickup_adress', 'pickup_name', 'pickup_phone',)

    pickup_adress = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Enter pick address',
        'class': 'w-100 py-2 px-2 rounded'
    }))
    pickup_name = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Enter pickup name',
        'class': 'w-100 py-2 px-2 rounded'
    }))
    pickup_phone = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Enter pickup phone',
        'class': 'w-100 py-2 px-2 rounded'
    }))

class OrderCreateStep3Form(forms.ModelForm):
    delivery_address = forms.CharField(required=True)
    delivery_name = forms.CharField(required=True)
    delivery_phone = forms.CharField(required=True)

    class Meta:
        model = Order
        fields = ('delivery_address', 'delivery_name', 'delivery_phone',)

    delivery_address = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Enter delivery address',
        'class': 'w-100 py-2 px-2 rounded'
    }))
    delivery_name = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Enter delivery name',
        'class': 'w-100 py-2 px-2 rounded'
    }))
    delivery_phone = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Enter delivery phone',
        'class': 'w-100 py-2 px-2 rounded'
    }))    

class OrderCreateStep4Form(forms.ModelForm):
    class Meta:
        model = Order
        fields = ('payment_methods', )

project/my_site/website/driver/forms.py
from django import forms
from django.contrib.auth.models import User
from website.models import Driver

class BasicUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = '__all__'

class BasicDriverForm(forms.ModelForm):
    class Meta:
        model = Driver
        fields = ('avatar', 'phone_number',)

project/my_site/website/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-50 py-2 px-2 rounded'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-50 py-2 px-2 rounded'
    }))

class SignupForm(UserCreationForm):
    first_name = forms.CharField(max_length=150)
    last_name = forms.CharField(max_length=150)

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2')

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-100 py-2 px-2 rounded'
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your email',
        'class': 'w-100 py-2 px-2 rounded'
    }))
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your first name',
        'class': 'w-100 py-2 px-2 rounded'
    }))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your last name',
        'class': 'w-100 py-2 px-4 rounded'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-100 py-2 px-4 rounded'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Password confirmation',
        'class': 'w-100 py-2 px-4 rounded'
    }))

class EditProfile(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name')



        

project/my_site/website/customer/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from website.customer import forms

from django.contrib import messages
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash

from website.models import Order
# Create your views here.
@login_required()
def home(request):
    return render(request, 'customer/customer_page.html')

@login_required(login_url='login/?next=/customer/')
def profile(request):
    user_form = forms.BasicUserForm(instance=request.user)
    customer_form = forms.BasicCustomerForm(instance=request.user.customer)
    password_form = PasswordChangeForm(request.user)

    if request.POST.get('action') == 'update_profile':
        if request.method == 'POST':
            user_form = forms.BasicUserForm(request.POST, instance=request.user)
            customer_form = forms.BasicCustomerForm(request.POST, request.FILES, instance=request.user.customer)

            if user_form.is_valid() and customer_form.is_valid():
                user_form.save()
                customer_form.save()
                return redirect(reverse('core:customer:home'))
            
    elif request.POST.get('action') == 'update_password':
        password_form = PasswordChangeForm(request.user, request.POST)
        if password_form.is_valid():
            user = password_form.save()
            update_session_auth_hash(request, user)
            return redirect(reverse('core:customer:home'))
        
    return render(request, 'customer/profile.html', {
        'user_form' : user_form,
        'customer_form': customer_form,
        'password_form': password_form,
    })

@login_required(login_url='login/?next=/customer/')
def create_order(request):
    current_customer = request.user.customer
    medium_price = 25000.0
    large_price = 35000.0
    creating_order = Order.objects.filter(customer=current_customer, status=Order.CREATING_STATUS).last()
    step1_form = forms.OrderCreateStep1Form(instance=creating_order)
    step2_form = forms.OrderCreateStep2Form(instance=creating_order)
    step3_form = forms.OrderCreateStep3Form(instance=creating_order)
    step4_form = forms.OrderCreateStep4Form(instance=creating_order)
    
    if request.method == 'POST':
        if request.POST.get('step') == '1':
            step1_form = forms.OrderCreateStep1Form(request.POST, request.FILES, instance=creating_order)
            if step1_form.is_valid():
                creating_order = step1_form.save(commit=False)
                creating_order.customer = current_customer
                if creating_order.size == 'medium':
                    creating_order.price = medium_price 
                elif creating_order.size == 'large':
                     creating_order.price = large_price
                creating_order.save()
                return redirect(reverse('core:customer:create_order'))
            
        elif request.POST.get('step') == '2':
            step2_form = forms.OrderCreateStep2Form(request.POST, instance=creating_order)
            if step2_form.is_valid():    
                creating_order = step2_form.save()
                return redirect(reverse('core:customer:create_order'))
            
        elif request.POST.get('step') == '3':
            step3_form = forms.OrderCreateStep3Form(request.POST, instance=creating_order)
            if step3_form.is_valid():    
                creating_order = step3_form.save()
                return redirect(reverse('core:customer:create_order'))

        elif request.POST.get('step') == '4':
            step4_form = forms.OrderCreateStep4Form(request.POST, instance=creating_order)
            if step4_form.is_valid(): 
                creating_order.status = Order.PROCESSING_STATUS
                
                creating_order = step4_form.save()
                return redirect(reverse('core:customer:orders'))

    if not creating_order:
        current_step = 1
    elif creating_order.delivery_name:
        current_step = 4
    elif creating_order.pickup_name:
        current_step = 3
    else:
        current_step = 2

    return render(request, 'customer/create_order.html', {   
        'order' : creating_order,
        'current_step': current_step,
        'step1_form' : step1_form,
        'step2_form' : step2_form,
        'step3_form' : step3_form,
        'step4_form' : step4_form,
    })
    
@login_required(login_url='login/?next=/customer/')
def orders(request):
    order = Order.objects.filter(
        customer=request.user.customer,
        status__in = [
            Order.PROCESSING_STATUS,
            Order.PICKING_STATUS,
            Order.DELIVERY_STATUS,
        ]
    )

    return render(request, 'customer/orders.html', {
        'order': order
    })

@login_required(login_url='login/?next=/customer/')
def archived_orders(request):
    order = Order.objects.filter(
        customer=request.user.customer,
        status__in = [
            Order.COMPLETED_STATUS,
            Order.CANCELED_STATUS,
        ]
    )

    return render(request, 'customer/orders.html', {
        'order': order
    })

@login_required(login_url='login/?next=/customer/')
def details(request, order_id):
    order = Order.objects.get(id=order_id)

    if request.method == 'POST' and order.status == Order.PROCESSING_STATUS:
        order.status = Order.CANCELED_STATUS
        order.save()
        return redirect(reverse('core:customer:archived'))

    return render(request, 'customer/details.html', {
        'order': order
    })

project/my_site/website/driver/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from website.driver import forms
import pandas as pd
import numpy as np
from website.models import Order

@login_required()
def driver_page(request):
    return render(request, 'driver/driver_page.html')

@login_required(login_url='/signup/?next=/driver/')
def available_jobs(request, id):
    job = Order.objects.get(id=id)
    
    if not job:
        return redirect(reverse('core:driver:jobs'))
    
    if request.method == 'POST' and job.status == Order.PROCESSING_STATUS:
        job.driver = request.user.driver
        job.status = Order.PICKING_STATUS
        job.save()
        return redirect(reverse('core:driver:myjob'))
    
    return render(request, 'driver/available_jobs.html', {
         'item' : job
    })

@login_required(login_url='/signup/?next=/driver/')
def jobs(request):
    job = Order.objects.filter(status=Order.PROCESSING_STATUS)

    return render(request, 'driver/jobs.html', {
        'job': job
    })

@login_required(login_url='/signup/?next=/driver/')
def myjob(request):
    job = Order.objects.filter(
        driver=request.user.driver,
        status__in = [
            Order.PICKING_STATUS,
            Order.DELIVERY_STATUS,
        ]
    )

    if request.method == 'POST':
        if request.POST.get('status') == 'delivery':
            for j in job:
                j.status = Order.DELIVERY_STATUS
                j.save()
                return redirect(reverse('core:driver:myjob'))
        elif request.POST.get('status') == 'cancel':
            for j in job:
                j.status = Order.PROCESSING_STATUS
                j.save()
                return redirect(reverse('core:driver:jobs'))
        elif request.POST.get('status') == 'complete':
            for j in job:
                j.status = Order.COMPLETED_STATUS
                j.save()
                return redirect(reverse('core:driver:home'))

    return render(request, 'driver/my_job.html', {
        'myjob' : job
    })

@login_required(login_url='/signup/?next=/driver/')
def dashboard(request):
    driver = request.user.driver
    
    order = Order.objects.filter(
        driver = driver,
        status__in = [
            Order.COMPLETED_STATUS
        ]
    )
    order_item = Order.objects.filter(
        driver = driver,
        status__in = [
            Order.COMPLETED_STATUS
        ]
    ).values()

    df = pd.DataFrame(order_item).sort_values('size', ascending=False)
    df_name = df['name'].tolist()
    df_price = df['price'].tolist()
    df_size = df['size'].value_counts().tolist()
    quantity = df.shape[0]

    for item in order:
        driver.earnings += item.price
         

    return render(request, 'driver/dashboard.html', {
        'order' : order,
        'df' : df,
        'df_name': df_name,
        'df_price': df_price,
        'df_size' : df_size,
        'earnings_month' : driver.earnings,
        'quantity' : quantity
    })

project/my_site/website/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import SignupForm, EditProfile
from django.urls import reverse



# Create your views here.
def index(request):
    return render(request, 'core/index.html')

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            
            return redirect('/login/')
    else:
        form = SignupForm()    
    
    context = {
            'form' : form
    }
    
    return render(request, 'core/signup.html', context)

project/my_site/website/templates/core/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  
  <!-- Boostrap 4 -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <!-- Fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@500&display=swap" rel="stylesheet">
  <!-- Icons -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">

  <!-- Title -->
  <title>{% block title %}Welcome{% endblock %} | HF</title>
  {% block head %}{%endblock%}
</head>

<body style="width: auto; height: auto;">

  <!-- Navigation -->
  <nav class="navbar {% if not request.user.is_authenticated%} navbar-expand-lg {% endif %} navbar-dark bg-warning">
    <div class="container-fluid">
      <div class="">
        <a class="navbar-brand p-4  text-dark" href="/">Horizon Freight</a>
      </div>
      {% if not request.user.is_authenticated %}
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01"
          aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarColor01">
          <ul class="navbar-nav me-auto">
            <li class="nav-item {% if request.GET.next != '/driver/' %} active {% endif %}">
              <a class="nav-link text-dark" href="/login/?next=/customer/"> Customer </a>
            </li>
            <li class="nav-item {% if request.GET.next == '/driver/' %} active {% endif %}"></li>
              <a class="nav-link text-dark" href="/login/?next=/driver/">Driver</a>
            </li>
          </ul>
        </div>
        {% else %}
              <form class="form-inline">
                <span class="mr-4">{{ request.user.get_full_name|title }}</span>
                <button type="button" class="btn btn-outline-light"><a href="{% url 'core:logout' %}" class="text-decoration-none text-dark">Log out</a></button>
              </form>
        {% endif %}
      
    </div> 
  </nav>

  <!-- Content -->
  <div style="height: 1600px;">
    {% block content %}
      <div class="container">
        <div class="row">

          <div class="col-lg-12">
            <h1 class="text-center mb-5 mt-5">
              Welcome to Horizon Freight
            </h1>
          </div> 

          <div class="col-lg-6 mb-4">
            <div class="card w-100" style="width: 18rem;">
              <div class="card-body">
                <h5 class="card-title">Customer</h5> 
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                <button class="btn bg-info rounded"><a href="/signup/" class="card-link text-decoration-none text-light ">Register</a></button>
                <button class="btn bg-warning rounded"><a href="{% url 'core:customer:home'%}" class="card-link text-decoration-none text-dark ">Details</a></button>
              </div>
            </div>
          </div>

          <div class="col-lg-6 mb-4">
            <div class="card w-100" style="width: 18rem;">
              <div class="card-body">
                <h5 class="card-title">Driver</h5>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                <button class="btn bg-info rounded"><a href="/signup/" class="card-link text-decoration-none text-light ">Register</a></button>
                <button class="btn bg-warning rounded"><a href="{% url 'core:driver:home'%}" class="card-link text-decoration-none text-dark">Details</a></button>
              </div>
            </div>
          </div>

        </div>
        
      </div>
      
      
    {% endblock %}
   
  <!-- Footer -->
  <footer class="mt-5 bg-dark text-white  mw-50">
    <div class="d-flex justify-content-around">
      <div class="">
        <h3 class="text-primary">Company</h3>
        <ul>
          <li>Intro</li>
          <li>Help Center</li>
          <li>Terms Of Use</li>
          <li>Privacy Policy</li>

        </ul>
      </div>

      <div class="w-50">
        <h3 class="text-primary">About</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore
          magna aliqua. Maecenas sed enim ut sem viverra aliquet eget sit amet. Netus et malesuada fames ac turpis
          egestas maecenas. Pellentesque adipiscing commodo elit at imperdiet. Egestas integer eget aliquet nibh
          praesent tristique magna sit. Massa placerat duis ultricies lacus sed.
          Quisque egestas diam in arcu cursus euismod quis. Volutpat est velit egestas dui. Sit amet mattis vulputate
          enim nulla. Tempus urna et pharetra pharetra massa. Eget lorem dolor sed viverra ipsum nunc. Mauris in aliquam
          sem fringilla. Nisl purus in mollis nunc sed id semper risus. Maecenas volutpat blandit aliquam etiam erat.
          Facilisi etiam dignissim diam quis enim lobortis scelerisque.
        </p>
      </div>

      <div class="">
        <h3 class="text-primary">Contact</h3>
        <div class="my-3"><i class="fa-brands fa-facebook fa-2xl"><a href="#" ></a></i></div>
        <div class="my-3"><i class="fa-brands fa-instagram fa-2xl"><a href="#"></a></i></div> 
        <div class="my-3"><i class="fa-brands fa-twitter fa-2xl"><a href="#"></a></i></div>
        

      </div>
    </div>
  </footer>

  
</body>

</html>

project/my_site/website/templates/core/login.html
{% extends 'core/index.html' %}

{% block title %} Login {% endblock %}

{% block content %}
<div class="mb-5"></div>
<div class="w-50 mt-6 m-6 mx-auto p-6 bg-light rounded ">
    <h4 class="text-center text-uppercase mb-3 mt-3">
        <b>
            {% if request.GET.next != '/driver/' %}
            Customer
            {% else %}
            Driver
            {% endif %}
        </b>
    </h4>
    <form action="" method="post">
        {% csrf_token %}

        <div class="d-flex justify-content-center mb-3">
            <br>
            <label class="m-2 ">Username</label>
            {{ form.username }}
        </div>

        <div class="d-flex justify-content-center mb-3">
            <label class="d-inline-block m-2">Password</label><br>
            {{ form.password }}
        </div>


        <button class="btn btn-outline-success m-3 d-flex algin-middle" type="submit">Submit</button>

        {% if form.error or form.non_field_errors %}
            <div class="mb-3 p-6 bg-warning text-black rounded">
                {% for field in form %}
                    {{ form.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}
    </form>

</div>
{% endblock %}

project/my_site/website/templates/core/signup.html
{% extends 'core/index.html' %}

{% block title %}Sign up{% endblock %}

{% block content %}
    <div class="mb-5"></div>
    <div class="w-50 mt-6 m-6 mx-auto p-6 bg-light rounded ">
        <h1 class="d-flex justify-content-center"> Sign up </h1>

        <form action="" method="post">
            {% csrf_token %}
            <div class="mb-3">
                
                <label class="m-2 d-inline-block">Username</label><br>
                {{ form.username }}
                
            </div>

            <div class="mb-3">
                
                <label class="m-2 d-inline-block">First name</label><br>
                {{ form.first_name }}
                
            </div>

            <div class="mb-3">
                
                <label class="m-2 d-inline-block">Last name</label><br>
                {{ form.last_name }}
                
            </div>

            <div class="mb-3">
                <label class="m-2 d-inline-block">Email</label><br>
                {{ form.email }}
            </div>

            <div class="mb-3">
                
                <label class="m-2 d-inline-block">Password</label><br>
                {{ form.password1 }}
                
            </div>
            
            <div class="mb-3">
                <label class="m-2">Password confirmation</label><br>
                {{ form.password2 }}
                
            </div>
            <div class="d-flex justify-content-center">
                <button class="w-50 m-4 btn  btn-outline-success" type="submit">Submit</button>
            </div>
            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-warning rounded text-white">
                    {% for field in form %}
                        {{ form.errors }}
                    {% endfor %}

                    {{ form.non_field_errors }}
                </div>
            {% endif %}
        </form>

    </div>
{% endblock %}